### ISSUE TITLE
Setup from Scratch

### ISSUE THREAD

**Issue by rwieruch** [the-road-to-learn-react/react-mobx-local-state-example#1]
Since it is a tedious task to upgrade all dependencies of an ejected create-react-app, maybe someone wants to help to set up this project with a fresh create-react-app version from scratch, ejecting it, installing MobX to it, and adding the implementation details of the App from before again.

**Comment by brianabaker** [comment]
Hi! By implementation details do you mean what's written currently in the readme.md file? I'd like to claim this!

**Comment by rwieruch** [comment]
Basically everything in src/ folder should be the same. But yes, also the README.md in the end :)

I think the simplest way to do it would be the following steps:

- fork the repository
- erase everything (except for the .git folder)
- create a new React app with create-react-app 2
- [add MobX to it](https://www.robinwieruch.de/create-react-app-mobx-decorators/) whereas I think eject is still needed for decorators
- make it work as before with the implementation in the src/ folder files
- copy the README.md, .gitignore and .travis.yml (if there is one) from the previous project to the new project
- create a PR and let's merge it 🚀 

Notes:

- don't worry about the registerServiceWorker.js file, because this is differently named in create-react-app 2

If you have time, it would be great to see someone else working on this :) The project is used by React beginners to dip their toes into MobX.

The same issue can be found for two other MobX projects over here: 

* https://github.com/taming-the-state-in-react/react-mobx-firebase-authentication/issues/4
* https://github.com/taming-the-state-in-react/react-mobx-hackernews/issues/1

**Comment by brianabaker** [comment]
Great I'll get right to it!

**Comment by brianabaker** [comment]
I ejected and I'm working on it! Thank you for your help!

**Comment by rwieruch** [comment]
Thanks for your helo @brianabaker 🎉
